const data = {
  name: 'роцк',
  cover:
    'https://is5-ssl.mzstatic.com/image/thumb/SG-S3-US-Std-Image-000002/v4/eb/be/38/ebbe3865-7207-d8bc-2c08-29eb39365ae5/image/760x760cc.jpg',
  url: 'https://music.apple.com/ru/playlist/%D1%80%D0%BE%D1%86%D0%BA/pl.u-PDb4zlBFL19qGpg',
  tracklist: [
    {
      name: 'Find Me',
      artist: 'Kings of Leon',
      artworkLink:
        ' https://is2-ssl.mzstatic.com/image/thumb/Music123/v4/eb/91/3b/eb913b33-7641-31b9-b039-b9c1dd499fab/886446009971.jpg/80x80bb.jpg',
      id: 0,
      willProcessed: false,
      wasFound: false,
    },
    {
      name: 'Waste a Moment',
      artist: 'Kings of Leon',
      artworkLink:
        ' https://is2-ssl.mzstatic.com/image/thumb/Music123/v4/eb/91/3b/eb913b33-7641-31b9-b039-b9c1dd499fab/886446009971.jpg/80x80bb.jpg',
      id: 1,
      willProcessed: false,
      wasFound: false,
    },
    {
      name: 'Teenager',
      artist: 'MONA',
      artworkLink:
        ' https://is1-ssl.mzstatic.com/image/thumb/Music118/v4/66/29/9b/66299bb3-690b-59a9-e83c-29f6a60739b3/00602527709215.rgb.jpg/80x80bb.jpg',
      id: 2,
      willProcessed: false,
      wasFound: false,
    },
    {
      name: 'Beautiful Day',
      artist: 'U2',
      artworkLink:
        ' https://is4-ssl.mzstatic.com/image/thumb/Music128/v4/5d/e4/f0/5de4f036-1356-8f6e-a8d9-806b57d71cc4/00602557667240.rgb.jpg/80x80bb.jpg',
      id: 3,
      willProcessed: false,
      wasFound: false,
    },
    {
      name: 'Рокстар (feat. WLVS & Zest)',
      artist: 'BIG RUSSIAN BOSS',
      artworkLink:
        ' https://is2-ssl.mzstatic.com/image/thumb/Music122/v4/ec/58/64/ec5864a1-8a32-e28a-73be-aa636b88eb7b/cover.jpg/80x80bb.jpg',
      id: 4,
      willProcessed: false,
      wasFound: false,
    },
    {
      name: 'Wasted',
      artist: 'Kasabian',
      artworkLink:
        ' https://is5-ssl.mzstatic.com/image/thumb/Music122/v4/01/4c/f4/014cf4e2-405b-d7bf-e444-84d4e24e45d0/886446403656.jpg/80x80bb.jpg',
      id: 5,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Dance With Somebody',
      artist: 'Mando Diao',
      artworkLink:
        ' https://is5-ssl.mzstatic.com/image/thumb/Music128/v4/6a/87/15/6a8715fd-61e6-8c42-583d-cbbc7c47faa9/00602527022222.rgb.jpg/80x80bb.jpg',
      id: 6,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Bohemian Like You',
      artist: 'The Dandy Warhols',
      artworkLink:
        ' https://is1-ssl.mzstatic.com/image/thumb/Music118/v4/ba/0b/4a/ba0b4a66-3d5f-897d-cf23-bc5a8a59db47/05099996539750.rgb.jpg/80x80bb.jpg',
      id: 7,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Golden Skans',
      artist: 'Klaxons',
      artworkLink:
        ' https://is2-ssl.mzstatic.com/image/thumb/Music128/v4/12/2c/0e/122c0e0e-b658-7847-cf86-458a8258a461/00602517206526.rgb.jpg/80x80bb.jpg',
      id: 8,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'A Million Ways',
      artist: 'OK Go',
      artworkLink:
        ' https://is1-ssl.mzstatic.com/image/thumb/Music128/v4/73/68/67/7368674e-648b-ea04-2060-33bfb0b99339/00724357880053.rgb.jpg/80x80bb.jpg',
      id: 9,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Down in the Past',
      artist: 'Mando Diao',
      artworkLink:
        ' https://is3-ssl.mzstatic.com/image/thumb/Music3/v4/23/87/a8/2387a887-a4a0-eb86-f7bc-137e22200c33/724386646156.jpg/80x80bb.jpg',
      id: 10,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Coming of Age',
      artist: 'Foster the People',
      artworkLink:
        ' https://is5-ssl.mzstatic.com/image/thumb/Music6/v4/5e/5e/35/5e5e35d8-ce17-8c57-76f5-33de5d4ddf83/886444398169.jpg/80x80bb.jpg',
      id: 11,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Help',
      artist: 'Papa Roach',
      artworkLink:
        ' https://is1-ssl.mzstatic.com/image/thumb/Music118/v4/dc/26/61/dc26613b-198c-7691-aa8f-c08e7ba38a3d/849320018179.png/80x80bb.jpg',
      id: 12,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Space & Time',
      artist: 'FMLYBND',
      artworkLink:
        ' https://is4-ssl.mzstatic.com/image/thumb/Music118/v4/c7/89/35/c7893553-d614-1428-498d-6b3f25493930/859715878080_cover.jpg/80x80bb.jpg',
      id: 13,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Broken Promises',
      artist: 'Phoenix Effect',
      artworkLink:
        ' https://is3-ssl.mzstatic.com/image/thumb/Music/e7/6d/2c/mzi.regdizhw.jpg/80x80bb.jpg',
      id: 14,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'King See No Evil',
      artist: 'Phoenix Effect',
      artworkLink: '',
      id: 15,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Yellow',
      artist: 'Coldplay',
      artworkLink: '',
      id: 16,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Shiver',
      artist: 'Coldplay',
      artworkLink: '',
      id: 17,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'High Speed',
      artist: 'Coldplay',
      artworkLink: '',
      id: 18,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: "Everything's Not Lost",
      artist: 'Coldplay',
      artworkLink: '',
      id: 19,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'In My Place',
      artist: 'Coldplay',
      artworkLink: '',
      id: 20,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Clocks',
      artist: 'Coldplay',
      artworkLink: '',
      id: 21,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Talk',
      artist: 'Coldplay',
      artworkLink: '',
      id: 22,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Speed of Sound',
      artist: 'Coldplay',
      artworkLink: '',
      id: 23,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Lost!',
      artist: 'Coldplay',
      artworkLink: '',
      id: 24,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Violet Hill',
      artist: 'Coldplay',
      artworkLink: '',
      id: 25,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Viva La Vida',
      artist: 'Coldplay',
      artworkLink: '',
      id: 26,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Strawberry Swing',
      artist: 'Coldplay',
      artworkLink: '',
      id: 27,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Love Is Noise',
      artist: 'The Verve',
      artworkLink: '',
      id: 28,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Bitter Sweet Symphony',
      artist: 'The Verve',
      artworkLink: '',
      id: 29,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Lucky Man',
      artist: 'The Verve',
      artworkLink: '',
      id: 30,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Wonderwall',
      artist: 'Oasis',
      artworkLink: '',
      id: 31,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Live Forever',
      artist: 'Oasis',
      artworkLink: '',
      id: 32,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Talk Tonight',
      artist: 'Oasis',
      artworkLink: '',
      id: 33,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Rope',
      artist: 'Foo Fighters',
      artworkLink: '',
      id: 34,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Ruby',
      artist: 'Kaiser Chiefs',
      artworkLink: '',
      id: 35,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: "Love's Not a Competition (But I'm Winning)",
      artist: 'Kaiser Chiefs',
      artworkLink: '',
      id: 36,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Under Pressure (feat. David Bowie)',
      artist: 'Queen',
      artworkLink: '',
      id: 37,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Animals',
      artist: 'Nickelback',
      artworkLink: '',
      id: 38,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Called Out In the Dark',
      artist: 'Snow Patrol',
      artworkLink: '',
      id: 39,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Maybe Tomorrow',
      artist: 'Stereophonics',
      artworkLink: '',
      id: 40,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Amsterdam',
      artist: 'Макс Корж',
      artworkLink: '',
      id: 41,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Любимая песня твоей сестры',
      artist: 'Пошлая Молли',
      artworkLink: '',
      id: 42,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: "If There's a Rocket Tie Me to It",
      artist: 'Snow Patrol',
      artworkLink: '',
      id: 43,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Take Back the City',
      artist: 'Snow Patrol',
      artworkLink: '',
      id: 44,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Бритни Спирс',
      artist: 'Noize MC',
      artworkLink: '',
      id: 45,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Честное слово!',
      artist: 'Noize MC',
      artworkLink: '',
      id: 46,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Жирная корова',
      artist: 'Noize MC',
      artworkLink: '',
      id: 47,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Нету паспорта (feat. Давид Казарян)',
      artist: 'Noize MC',
      artworkLink: '',
      id: 48,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Чёрное солнце',
      artist: 'Би-2',
      artworkLink: '',
      id: 49,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Аренби!!!',
      artist: 'Noize MC',
      artworkLink: '',
      id: 50,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Lightsabre C*********g Blues',
      artist: 'Mclusky',
      artworkLink: '',
      id: 51,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'She Loves Me Not',
      artist: 'Papa Roach',
      artworkLink: '',
      id: 52,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: '...To Be Loved',
      artist: 'Papa Roach',
      artworkLink: '',
      id: 53,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Сигареты и кофе',
      artist: 'Сегодняночью',
      artworkLink: '',
      id: 54,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Танцуй',
      artist: 'Сегодняночью',
      artworkLink: '',
      id: 55,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Magic Carpet Ride',
      artist: 'Steppenwolf',
      artworkLink: '',
      id: 56,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Make Some Noize (Single Edit)',
      artist: 'Noize MC',
      artworkLink: '',
      id: 57,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'My Number',
      artist: 'Foals',
      artworkLink: '',
      id: 58,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Inhaler',
      artist: 'Foals',
      artworkLink: '',
      id: 59,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'What You Know',
      artist: 'Two Door Cinema Club',
      artworkLink: '',
      id: 60,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Now That the Magic Has Gone',
      artist: 'Joe Cocker',
      artworkLink: '',
      id: 61,
      willProcessed: true,
      wasFound: false,
    },
    { name: 'One', artist: 'U2', artworkLink: '', id: 62, willProcessed: true, wasFound: false },
    {
      name: 'Georgy Porgy',
      artist: 'Toto',
      artworkLink: '',
      id: 63,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Carry Me',
      artist: 'Phoenix Effect',
      artworkLink: '',
      id: 64,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: "I Don't Want to Miss a Thing",
      artist: 'Aerosmith',
      artworkLink: '',
      id: 65,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'I Will Possess Your Heart',
      artist: 'Death Cab for Cutie',
      artworkLink: '',
      id: 66,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'I Just Wanna Live',
      artist: 'Good Charlotte',
      artworkLink: '',
      id: 67,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'The River (feat. M. Shadows & Synyster Gates)',
      artist: 'Good Charlotte',
      artworkLink: '',
      id: 68,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'The Pretender',
      artist: 'Foo Fighters',
      artworkLink: '',
      id: 69,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: "You're the Best Thing About Me",
      artist: 'U2',
      artworkLink: '',
      id: 70,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: "You've Got the Love",
      artist: 'Florence + the Machine',
      artworkLink: '',
      id: 71,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'The Man',
      artist: 'The Killers',
      artworkLink: '',
      id: 72,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: "You're In Love With a Psycho",
      artist: 'Kasabian',
      artworkLink: '',
      id: 73,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Rumble and Sway',
      artist: 'Jamie N Commons',
      artworkLink: '',
      id: 74,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Roses',
      artist: 'Poets of the Fall',
      artworkLink: '',
      id: 75,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'I Write Sins Not Tragedies',
      artist: 'Panic! At the Disco',
      artworkLink: '',
      id: 76,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'New Perspective',
      artist: 'Panic! At the Disco',
      artworkLink: '',
      id: 77,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Something to Believe In',
      artist: 'Young the Giant',
      artworkLink: '',
      id: 78,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Lottery',
      artist: 'Jade Bird',
      artworkLink: '',
      id: 79,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'The Ballad of Mona Lisa',
      artist: 'Panic! At the Disco',
      artworkLink: '',
      id: 80,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Rx (Medicate)',
      artist: 'Theory of a Deadman',
      artworkLink: '',
      id: 81,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'New Perspective',
      artist: 'Panic! At the Disco',
      artworkLink: '',
      id: 82,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Take Me Out',
      artist: 'Franz Ferdinand',
      artworkLink: '',
      id: 83,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Испортить вам пати!',
      artist: 'Noize MC',
      artworkLink: '',
      id: 84,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'R U Mine?',
      artist: 'Arctic Monkeys',
      artworkLink: '',
      id: 85,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Любимый цвет',
      artist: 'Noize MC',
      artworkLink: '',
      id: 86,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Do I Wanna Know?',
      artist: 'Arctic Monkeys',
      artworkLink: '',
      id: 87,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Heavydirtysoul',
      artist: 'twenty one pilots',
      artworkLink: '',
      id: 88,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Old Yellow Bricks',
      artist: 'Arctic Monkeys',
      artworkLink: '',
      id: 89,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Mr. Know-It-All',
      artist: 'Young the Giant',
      artworkLink: '',
      id: 90,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'The Past Recedes',
      artist: 'John Frusciante',
      artworkLink: '',
      id: 91,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Thnks Fr Th Mmrs',
      artist: 'Fall Out Boy',
      artworkLink: '',
      id: 92,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'The Take Over, The Breaks Over',
      artist: 'Fall Out Boy',
      artworkLink: '',
      id: 93,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Dance, Dance',
      artist: 'Fall Out Boy',
      artworkLink: '',
      id: 94,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Yeah Yeah Yeah',
      artist: 'New Politics',
      artworkLink: '',
      id: 95,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Dignity',
      artist: 'New Politics',
      artworkLink: '',
      id: 96,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Give Me Hope',
      artist: 'New Politics',
      artworkLink: '',
      id: 97,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Love Is a Drug',
      artist: 'New Politics',
      artworkLink: '',
      id: 98,
      willProcessed: true,
      wasFound: false,
    },
    {
      name: 'Burn',
      artist: 'New Politics',
      artworkLink: '',
      id: 99,
      willProcessed: true,
      wasFound: false,
    },
  ],
};

export default data;
